apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crypto-quote-server
spec:
  template:
    spec:
      containerConcurrency: 80
      containers:
        - image: aitjcize/crypto-quote-server:latest
          ports:
            containerPort: 80
            name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 80
            timeoutSeconds: 240
